"""Write docs/research8/SUMMARY.md from the aggregate JSON outputs of every research8 round.

python -m research8.summary
"""
import glob
import json
import os

DOCS = 'docs/research8'


def best(rules, key='c25', stat='sharpe', n=3):
    ok = [r for r in rules if key in r]
    return sorted(ok, key=lambda r: -r[key][stat])[:n]


def fmt(r, key='c25', tkey='t', scale=1.0, unit='%'):
    c = r[key]
    ci = c.get('ci') or c.get('ci_weekly')
    mean = c['mean'] * (100 if unit == '%' else 1e4)
    lo, hi = (x * (100 if unit == '%' else 1e4) for x in ci)
    return (f"`{r['rule']}`: n={r.get('n', r.get('n_trades', '?'))}, {mean:+.1f}{unit} [{lo:+.1f}, {hi:+.1f}], "
            f"Sharpe {c['sharpe']:.2f}, t {c.get(tkey, c.get('t_block', 0)):.2f}")


def main():
    L = ['# Research8 summary (generated by research8/summary.py)', '',
         'All numbers are aggregates computed by code. Costs: "25%" = a quarter of the quoted half-spread at entry '
         '(and at a mid exit); stock rules use basis points per side.', '']
    p1 = os.path.join(DOCS, 'phase1', 'dev.json')
    if os.path.exists(p1):
        d = json.load(open(p1))
        L += ['## Phase 1: stock return distributions', '', f"Freeze picks (dev): {d['freeze_picks']}", '']
        for m in sorted(set(d['freeze_picks'].values())):
            a = d['average'][m]
            L.append(f"- {m}: dev CRPS skill {a['crps_skill']:+.2%} [{a['crps_skill_ci'][0]:+.2%}, {a['crps_skill_ci'][1]:+.2%}], "
                     f"log-score gain {a['log_diff']:+.3f} nats, release-day CRPS skill {a.get('release_crps_skill', float('nan')):+.2%}")
        t = os.path.join(DOCS, 'phase1', 'test.json')
        if os.path.exists(t):
            dt_ = json.load(open(t))
            L += ['', 'Test (expanded names, 2023+):']
            for c, g in dt_['gates'].items():
                L.append(f"- {c} ({g['model']}): estimate {g['estimate']:+.4f} [{g['ci'][0]:+.4f}, {g['ci'][1]:+.4f}], passed={g['passed']} "
                         f"(lower bound {g['gate1_lower_bound_above_zero']}, every group {g['gate2_crps_every_group']}, coverage {g['gate3_coverage_90']})")
        L.append('')
    rounds = [('Phase 2 (A0): market price vs stock-only value', 'phase2', 'c25', 'sharpe', '%'),
              ('Approach R (ruler)', 'ruler', 'c25', 'sharpe', '%'),
              ('Cross-sectional long-short book', 'xsec', 'c25', 'sharpe', '%'),
              ('Approach T (direct trader)', 'trader', 'c25', 'sharpe', '%'),
              ('Pre-release long premium + model filter', 'prerel', 'c25', 'sharpe', '%'),
              ('Skew relative value', 'skew', 'c25', 'sharpe', '%'),
              ('Stock trades around releases', 'stockev', 'c10', 'sharpe', 'bp'),
              ('Daily panel volatility premium', 'daily', 'c25', 'sharpe', '%')]
    for title, folder, key, stat, unit in rounds:
        files = sorted(glob.glob(os.path.join(DOCS, folder, '*.json')))
        if not files:
            L += [f'## {title}', '', 'Not run yet.', '']
            continue
        L += [f'## {title}', '']
        for f in files:
            d = json.load(open(f))
            L.append(f"**{os.path.basename(f)}** ({d['sample']}): " +
                     (f"eligible {d.get('eligible')}, frozen {d.get('freeze_picks')}" if 'freeze_picks' in d else ''))
            if 'gates' in d:
                strong = [k for k, g in d['gates'].items() if g.get('strong')]
                weak = [k for k, g in d['gates'].items() if g.get('weak')]
                L.append(f"gates: strong {strong or 'none'}, weak {weak or 'none'}")
            for r in best(d['rules'], key, stat):
                L.append('- ' + fmt(r, key, unit=unit))
            L.append('')
    os.makedirs(DOCS, exist_ok=True)
    with open(os.path.join(DOCS, 'SUMMARY.md'), 'w') as s:
        s.write('\n'.join(L) + '\n')
    print('written', os.path.join(DOCS, 'SUMMARY.md'))


if __name__ == '__main__':
    main()
